---
- hosts: all
  become: yes

  tasks:
    - name: "Prepare default registries configuration"
      copy:
        src: "registries.yaml"
        dest: "/etc/rancher/k3s/registries.yaml"

    - name: "Restart k3s systemd service"
      systemd:
        name: "k3s"
        state: "restarted"
