---
- hosts: all
  become: yes

  tasks:
    - name: "Prepare default daemon configuration"
      copy:
        src: "daemon.json"
        dest: "/etc/docker/daemon.json"

    - name: "Restart docker systemd service"
      systemd:
        name: "docker"
        daemon_reload: yes
        state: "restarted"
